Update invitations
base-cms/id-me pull request #21
Opened 2019-06-24 18:28 UTC by solocommand

- [x] Ensures that users are sent to the invites page regardless of their logged-in state -- previously it would send a logged-in user to the organizations route.
- [x] Makes the edit profile modal available on all pages without changing the route, and forces the user to enter their name before continuing.

<img width="1024" alt="Screen Shot 2019-06-24 at 1 24 37 PM" src="https://user-images.githubusercontent.com/1778222/60042674-e3e79d00-9683-11e9-9a23-2a2ce78ae6c6.png">

2019-06-25 18:34 UTC, zarathustra323 requested changes

2019-06-25 18:34 UTC, zarathustra323 commented on services/manage/app/components/nav-context-user.js
> +      this.set('isModalOpen', true);
This will overwrite the initial `isModalOpen` computed property... is that intentional?

2019-06-25 18:34 UTC, zarathustra323 commented on services/manage/app/components/user/modal-form.js
> +        this.set('isModalOpen', false);
I'm slightly confused by this... the `closeModal()` function should already set this property, assuming it's bound to `@show`

2019-06-25 18:34 UTC, zarathustra323 commented on services/manage/app/components/user/modal-form.js
> +      this.set('isModalOpen', false);
Again, this shouldn't be necessary??

2019-06-25 18:34 UTC, zarathustra323 commented on services/manage/app/components/user/modal-form.js
> +        const input = { givenName, familyName, photoURL };
If the user can't input a photoURL via the form, why include it here?

2019-06-25 18:34 UTC, zarathustra323 commented on services/manage/app/routes/authenticate.js
> +    const isAuthenticated = await this.session.isAuthenticated;
The `isAuthenticated` property is a promise?

2019-06-25 18:34 UTC, zarathustra323 commented on services/manage/app/routes/manage/orgs/invites.js
> +    const { givenName, familyName } = get(model, '0.user');
Why is this hard set to the first item?

2019-06-25 18:34 UTC, zarathustra323 commented on services/manage/app/services/user.js
> +  profileShown: false,
Is there a way to shore some of this up - perhaps with different semantics (such as `hasValidUserData` or something?). `profileShown` seems to vague (it's hard for me to understand what it means)

2019-07-01 15:30 UTC, zarathustra323 commented
Invite user:
![image](https://user-images.githubusercontent.com/3289485/60448292-f2393a00-9bea-11e9-85ce-03c10e45140c.png)
![image](https://user-images.githubusercontent.com/3289485/60448299-f6fdee00-9bea-11e9-8699-b66a1b937928.png)

Invite email:
![image](https://user-images.githubusercontent.com/3289485/60448339-02e9b000-9beb-11e9-85a3-e2586b4c5a04.png)

Complete user profile (only when fields are missing):
![image](https://user-images.githubusercontent.com/3289485/60448374-109f3580-9beb-11e9-8e83-cc5149edc352.png)

View invite page (redirects to this automatically from invite email):
![image](https://user-images.githubusercontent.com/3289485/60448407-20b71500-9beb-11e9-9b7e-c876e3fe4cf4.png)

Invite list (if navigated to):
![image](https://user-images.githubusercontent.com/3289485/60448428-2ca2d700-9beb-11e9-93a5-3da6be3845cb.png)

2019-07-01 15:39 UTC, zarathustra323 approved these changes

2019-07-01 15:46 UTC, solocommand reviewed
Can't approve, but looks good.

2019-07-01 15:56 UTC, merged