Team activation
base-cms/id-me pull request #22
Opened 2019-06-24 19:48 UTC by solocommand

Stopgap until we add subscriptions, allows teams to be disabled without removing access roles or IP addresses.

Will require bulk update to set `active: true` on all existing teams before deployment

2019-06-24 19:56 UTC, zarathustra323 requested changes

2019-06-24 19:56 UTC, zarathustra323 commented on services/graphql/src/graphql/definitions/team.js
> +  active: Boolean!
If you allow this to be a nullable field, it won't break data if the field is missing

2019-06-24 19:56 UTC, zarathustra323 commented on services/application/src/actions/load-context.js
> +    active: true,
Set this to `${ ne: false }` and then it will immediately work without data migration

2019-06-24 20:39 UTC, solocommand commented
@zarathustra323 Added UI stuff and addressed previous comments

2019-06-24 20:44 UTC, zarathustra323 requested changes

2019-06-24 20:44 UTC, zarathustra323 commented on services/manage/app/templates/components/form-elements/toggle-button.hbs
> +  {{toggle.offLabel}}
The dual-label isn't necessary here. A single "Active" label is fine. Similar to NativeX:
![image](https://user-images.githubusercontent.com/3289485/60050726-edc6cb80-9696-11e9-8ddc-8c2604ce61b0.png)

2019-06-24 20:45 UTC, zarathustra323 requested changes

2019-06-24 20:45 UTC, zarathustra323 commented on services/manage/app/templates/components/team/modal-form.hbs
> +      <FormElements::ToggleButton @value={{model.active}} @onLabel="Active" @offLabel="Inactive" />
Ignore above and just remove the `@offLabel` prop

2019-06-25 18:37 UTC, zarathustra323 requested changes
In addition to these, can the toggle style itself be adjusted to use the bootstrap `$primary` color (e.g. blue instead of the default green)?

2019-06-25 18:37 UTC, zarathustra323 commented on services/manage/app/templates/components/team/modal-form.hbs
> +      <FormElements::ToggleButton @value={{model.active}} @onLabel="Active" />
While technically it doesn't matter, the new Ember docs want to use `this` when referencing a value in the containing component... as such `@value={{this.model.active}}` - i'm trying hard to switch to this style (though I forget at times)

2019-06-25 18:37 UTC, zarathustra323 commented on services/manage/app/templates/components/team/status.hbs
> +Status: <span class={{ labelClass }}>{{ label }}</span>
Remove spaces

2019-06-25 20:14 UTC, solocommand commented
Updated screenshots
<img width="1035" alt="Screen Shot 2019-06-25 at 3 14 18 PM" src="https://user-images.githubusercontent.com/1778222/60129980-ef0dfc00-975b-11e9-8fc7-a1cbc3f4686f.png">
<img width="1031" alt="Screen Shot 2019-06-25 at 3 14 13 PM" src="https://user-images.githubusercontent.com/1778222/60129981-ef0dfc00-975b-11e9-8ee4-0122f9bd0bbe.png">

2019-06-25 20:18 UTC, zarathustra323 approved these changes

2019-06-25 20:18 UTC, merged