User search implementation
base-cms/id-me pull request #23
Opened 2019-06-25 16:38 UTC by solocommand

@zarathustra323 WIP, but would like early feedback on the Graph/microservice implementation.
- [x] Adds microservice action to return paginated results based on search terms
  - Existing `matchForApp` does not support pagination, used for autocompleters
- [x] Adds definition/resolver for AppUser
  - Avoided going down the directive route due to needing something to signify the model/service
- [ ] Management implementation, make users searchable

GraphQL query/response
<img width="1200" alt="Screen Shot 2019-06-25 at 11 35 12 AM" src="https://user-images.githubusercontent.com/1778222/60116453-a5aeb400-973d-11e9-9740-4fa60b9b38b1.png">

Mgmt UI
(NYI)

2019-06-25 18:40 UTC, zarathustra323 requested changes

2019-06-25 18:40 UTC, zarathustra323 commented on packages/mongoose-plugins/src/application-plugin.js
> +      query: { applicationId, ...query },
This needs to be reversed, otherwise the `applicationId` can be overridden by the query

2019-06-25 18:40 UTC, zarathustra323 commented on packages/utils/src/actions/index.js
> +  matchManyForApp,
What's the distinction here? `matchForApp` and `matchManyForApp` both return multiple results. These should be consolidated.

2019-06-25 18:40 UTC, zarathustra323 commented on packages/utils/src/actions/match-many-for-app.js
> +};
Consolidate this logic into `matchForApp`

2019-06-25 18:40 UTC, zarathustra323 commented on packages/utils/src/index.js
> +  buildRegex,
Shouldn't need to put this here anymore...

2019-06-25 18:42 UTC, zarathustra323 requested changes
"Fix" the match input group controls so that the left-side button (next to the input) is not rounded. Also, the input itself needs drop shadow added to it to the match the buttons

2019-06-25 18:43 UTC, zarathustra323 requested changes
Also, we no longer need the `Show: 24` button (nor the limit param) as these pages are now infinite scroll

2019-06-25 19:28 UTC, solocommand commented
Removed limit, fixed box shadow and border radius
<img width="1036" alt="Screen Shot 2019-06-25 at 2 27 19 PM" src="https://user-images.githubusercontent.com/1778222/60127293-6db36b00-9755-11e9-83e1-132519bf97df.png">

2019-06-25 20:34 UTC, zarathustra323 requested changes

2019-06-25 20:34 UTC, zarathustra323 commented on packages/utils/src/actions/match-for-app.js
> +    sort: { ...defaultSort, sort },
Spread `...sort`

2019-06-25 20:34 UTC, zarathustra323 commented on services/graphql/src/graphql/definitions/app-user.js
> +  appUsers(pagination: PaginationInput = {}, sort: AppUserSortInput = {}): AppUserConnection! @requiresAppRole
The `pagination` and `sort` args should be combined into a single input. See
https://github.com/base-cms/id-me/blob/1d512f268b539fdde983aace151655810edb7dd6/services/graphql/src/graphql/definitions/team.js#L7
And
https://github.com/base-cms/id-me/blob/1d512f268b539fdde983aace151655810edb7dd6/services/graphql/src/graphql/definitions/team.js#L60

2019-06-25 20:34 UTC, zarathustra323 commented on services/graphql/src/graphql/definitions/app-user.js
> +  matchAppUsers(input: MatchAppUsersQueryInput!, pagination: PaginationInput = {}, sort: AppUserSortInput = {}): AppUserConnection! @requiresAppRole
Same as above.

2019-06-25 20:36 UTC, zarathustra323 requested changes

2019-06-25 20:36 UTC, zarathustra323 commented on services/graphql/src/graphql/resolvers/access-level.js
> +    matchAccessLevels: async (_, { input }, { app }) => {
You might as well convert this to use a `AccessLevelConnection` so it's consistent with everything else.

2019-07-01 17:37 UTC, zarathustra323 commented
Default view:
![image](https://user-images.githubusercontent.com/3289485/60455734-e0609280-9bfc-11e9-8fc2-66f3af68443c.png)

Search phrase view:
![image](https://user-images.githubusercontent.com/3289485/60455752-ece4eb00-9bfc-11e9-8fac-267a91ae06c2.png)

Search phrase focused view (no Chrome X button):
![image](https://user-images.githubusercontent.com/3289485/60455766-f8d0ad00-9bfc-11e9-8fda-57c852b13e6d.png)

2019-07-01 17:40 UTC, zarathustra323 approved these changes

2019-07-01 17:43 UTC, merged