AppUser export support
base-cms/id-me pull request #37
Opened 2020-01-28 22:15 UTC by solocommand

Adds backend support to download an export of user data by `applicationId`.

@zarathustra323 You said to move it out of the GraphQL service -- The actual export is done via the application service, but a route is added to the GraphQL Express app to actually do the download of the CSV data.

I did this primarily because this will ultimately be a component within the interface, and this allows access to the download action from the browser without adding additional rancher routing & container overhead.

Thoughts?

2020-01-31 16:46 UTC, zarathustra323 requested changes

2020-01-31 16:46 UTC, zarathustra323 commented on services/export/src/actions/user/export-for-app.js
> +    const users = await AppUser.find({ applicationId }, projection);
Use application service

2020-01-31 16:46 UTC, zarathustra323 commented on services/export/src/actions/user/export-for-app.js
> +    const filename = `export-${applicationId}-${Date.now()}.csv`;
`app-user-export-${applicationId}-${Date.now()}.csv`

2020-01-31 16:46 UTC, zarathustra323 commented on services/export/src/s3.js
> +    Expires: Math.floor(Date.now().valueOf() / 1000),
Times 30 days

2020-01-31 16:46 UTC, zarathustra323 commented on services/manage/app/components/button/export.js
> +  context: inject(),
I believe this can be mixed in.

2020-01-31 16:51 UTC, zarathustra323 requested changes

2020-01-31 16:51 UTC, zarathustra323 commented on services/manage/app/components/button/export.js
> +  errorNotifier: inject(),
Move the action logic outside of the component

2020-01-31 22:48 UTC, solocommand commented
@zarathustra323 all changes implemented

2020-02-03 15:51 UTC, zarathustra323 requested changes

2020-02-03 15:51 UTC, zarathustra323 commented on services/export/package.json
> +    "mongoose": "^5.5.11",
Remove mongoose.

2020-02-03 15:51 UTC, zarathustra323 commented on services/export/src/utils/stream-results.js
> + * @param client      - The service client
```
@param {object} args The function args
@param {object} args.client
@param {string} args.action The service action
```

2020-02-03 15:51 UTC, zarathustra323 commented on services/export/src/utils/stream-results.js
> +  const nodes = getAsArray(data, 'edges').map(({ node }) => node);
`const nodes = getAsArray(data, 'edges').map(edge => edge.node);`

2020-02-03 15:51 UTC, zarathustra323 commented on services/export/src/utils/stream-results.js
> + * @param stream      - The input stream to send results to
`The JSON2CSV stream... yadda yadda`

2020-02-03 15:51 UTC, zarathustra323 commented on services/export/src/utils/stream-results.js
> +module.exports = async ({
`module.exports = executor`

2020-02-03 15:51 UTC, zarathustra323 commented on services/export/src/utils/stream-results.js
> +    limit,
`limit = 500`

2020-02-03 15:51 UTC, zarathustra323 commented on services/manage/app/templates/manage/orgs/view/apps/view/users.hbs
> +    <Button::Export @title="Export Users" @action={{action "export"}} />
`@click={{action "export"}}`

2020-02-03 15:51 UTC, zarathustra323 commented on services/manage/app/components/button/export.js
> +  async click() {
Remove this function

2020-02-03 15:51 UTC, zarathustra323 commented on services/export/src/actions/user/export-for-app.js
> +    await sendFailure({ email, error: e });
`sendFailure({ email, error: e }).catch(newrelic.noticeError)`

2020-02-03 16:55 UTC, zarathustra323 approved these changes

2020-02-03 16:57 UTC, merged